// Mobile export helpers. A PDF is produced from a themed HTML document via
// expo-print, then handed to the OS share sheet; the spreadsheet export is a
// UTF-8 CSV (opens directly in Excel / Numbers / Sheets) written to the cache
// dir and shared the same way. All interpolated user text is escaped.
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as FileSystem from "expo-file-system";

export function escHtml(s: string): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function csvCell(v: string | number): string {
  const s = String(v ?? "");
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function toCsv(header: string[], rows: (string | number)[][]): string {
  const lines = [header, ...rows].map((r) => r.map(csvCell).join(","));
  // Leading BOM so Excel opens it as UTF-8.
  return "\uFEFF" + lines.join("\r\n");
}

export async function shareCsv(csv: string, filename: string): Promise<void> {
  const uri = `${FileSystem.cacheDirectory}${filename}`;
  await FileSystem.writeAsStringAsync(uri, csv, {
    encoding: FileSystem.EncodingType.UTF8,
  });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "text/csv",
      dialogTitle: "Share expenses",
      UTI: "public.comma-separated-values-text",
    });
  }
}

export async function sharePdf(html: string): Promise<void> {
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: "Share expenses",
      UTI: "com.adobe.pdf",
    });
  }
}

export type PdfTable = { columns: string[]; rows: string[][] };

export function buildReportHtml(opts: {
  title: string;
  subtitle: string;
  summary: { label: string; value: string }[];
  table: PdfTable;
}): string {
  const summary = opts.summary
    .map(
      (s) =>
        `<div class="stat"><div class="stat-l">${escHtml(
          s.label
        )}</div><div class="stat-v">${escHtml(s.value)}</div></div>`
    )
    .join("");

  const head = opts.table.columns.map((c) => `<th>${escHtml(c)}</th>`).join("");
  const body =
    opts.table.rows
      .map((r) => `<tr>${r.map((c) => `<td>${escHtml(c)}</td>`).join("")}</tr>`)
      .join("") ||
    `<tr><td class="empty" colspan="${opts.table.columns.length}">No expenses in this period.</td></tr>`;

  return `<!doctype html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>${escHtml(
    opts.title
  )}</title><style>
    body { font-family: -apple-system, Roboto, "Segoe UI", Helvetica, Arial, sans-serif; color:#1c1917; margin:24px; }
    .brand { display:flex; align-items:center; gap:8px; }
    .dot { width:13px; height:13px; border-radius:5px; background:linear-gradient(135deg,#fb923c,#f59e0b); }
    .brand b { font-size:14px; background:linear-gradient(135deg,#f97316,#f59e0b); -webkit-background-clip:text; background-clip:text; color:transparent; }
    h1 { font-size:20px; margin:8px 0 2px; }
    .sub { color:#78716c; font-size:12px; margin-bottom:16px; }
    .stats { display:flex; flex-wrap:wrap; gap:8px; margin-bottom:18px; }
    .stat { border:1px solid #eee7e1; border-radius:10px; padding:8px 12px; background:#fdfbf9; }
    .stat-l { font-size:9px; text-transform:uppercase; letter-spacing:.5px; color:#a8a29e; }
    .stat-v { font-size:15px; font-weight:800; margin-top:2px; }
    table { width:100%; border-collapse:collapse; font-size:11px; }
    th { text-align:left; background:#fb923c; color:#fff; padding:6px 8px; -webkit-print-color-adjust:exact; }
    th:last-child, td:last-child { text-align:right; }
    td { padding:5px 8px; border-bottom:1px solid #f0ebe6; }
    tr:nth-child(even) td { background:#faf7f4; }
    td.empty { text-align:center; color:#a8a29e; padding:14px; }
    .foot { margin-top:22px; color:#a8a29e; font-size:10px; text-align:center; }
  </style></head><body>
    <div class="brand"><span class="dot"></span><b>Split+</b></div>
    <h1>${escHtml(opts.title)}</h1>
    <div class="sub">${escHtml(opts.subtitle)}</div>
    <div class="stats">${summary}</div>
    <table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>
    <div class="foot">Generated by Split+ · ${escHtml(new Date().toLocaleString())}</div>
  </body></html>`;
}
